### ISSUE TITLE
place order failed

### ISSUE THREAD

**Issue by nftdance** [drift-labs/gateway#64]
gate way trace log
request: PlaceOrdersRequest { orders: [PlaceOrder { market: Market { market_index: 0, market_type: Perp }, amount: 0.1, price: 175.35, user_order_id: 0, order_type: Limit, post_only: false, reduce_only: false, oracle_price_offset: None, max_ts: Some(1721734289) }] }
[2024-07-23T11:31:02Z DEBUG gateway] priority fee: 24403
[2024-07-23T11:31:03Z DEBUG gateway] sent tx (place_orders): YYX4aAjz2Taw6x9aD7PKwA8rCWPnpXN9c3K8BZXbTP2JSgi2myMk9ZoNtSzmBDk5PeA9u1Ea9UphUKfBCJm6Rtx
[2024-07-23T11:31:03Z DEBUG gateway] response: Ok(TxResponse { tx: "YYX4aAjz2Taw6x9aD7PKwA8rCWPnpXN9c3K8BZXbTP2JSgi2myMk9ZoNtSzmBDk5PeA9u1Ea9UphUKfBCJm6Rtx" })

log see send tx success,but can't find in  https://solscan.io/tx/YYX4aAjz2Taw6x9aD7PKwA8rCWPnpXN9c3K8BZXbTP2JSgi2myMk9ZoNtSzmBDk5PeA9u1Ea9UphUKfBCJm6Rtx

use grpc node is https://mainnet.helius-rpc.com

**Comment by jordy25519** [comment]
the `Ok` means it passed preflight checks and was broadcast but seems that the tx was not mined by the network. this can happen due to a low (relatively) CU price i.e from network congestion

can try to statically set a higher CU price per request `?computeUnitLimit=100000`
 https://github.com/drift-labs/gateway?tab=readme-ov-file#cu-price--limits
 
 additionally can poll this endpoint with the tx signature to know if it was mined or not, if it still 404s after 60s its probably dropped.
`curl localhost:8080/v2/transactionEvent/YYX4aAjz2Taw6x9aD7PKwA8rCWPnpXN9c3K8BZXbTP2JSgi2myMk9ZoNtSzmBDk5PeA9u1Ea9UphUKfBCJm6Rtx?subAccountId=0`
